packageExtensions:
  "@nestjs/common@*":
    dependencies:
      reflect-metadata: "*"
      rxjs: "*"
  "@nestjs/core@*":
    dependencies:
      rxjs: "*"
  "@nestjs/graphql@*":
    dependencies:
      graphql: "^15"
  apollo-server-core@*:
    dependencies:
      graphql: "^15"
  apollo-server-errors@*:
    dependencies:
      graphql: "^15"
  nestjs-pino@*:
    dependencies:
      "@nestjs/common": "*"
      pino: "*"
      rxjs: "*"
  typeorm@*:
    dependencies:
      pg: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-3.1.1.cjs
