packageExtensions:
  "@nestjs/apollo@*":
    dependencies:
      tslib: "*"
    peerDependencies:
      graphql: ^15.0.0
  nestjs-pino@*:
    peerDependencies:
      "@nestjs/common": ^8.0.0
      pino: ^6.0.0
      rxjs: ^7.0.0
  typeorm@*:
    dependencies:
      pg: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.1.1.cjs
